package com.rspsi.core.misc;

public enum ToolType {
	SELECT_TILE, PAINT_UNDERLAY, SELECT_OBJECT, SPAWN_OBJECT, DELETE_OBJECT, MODIFY_HEIGHT, PAINT_OVERLAY, PAINT_PATH, MOUNTAIN, COAST, SET_FLAGS, IMPORT_SELECTION
}
